export enum OnboardingStatus {
  ACTIVE='Active',
  ON_LEAVE='On Leave',
  DEACTIVATED='Deactivated',
}

export interface OnboardingItem {
  id: number;
  name: string;
  role: string;
  email: string;
  phone: string;
  status: OnboardingStatus;
}

export const OnboardingDummyItems: OnboardingItem[] = [
  {
    id: 1,
    name: "John Doe",
    role: "Healthcare Assistant",
    email: "johndoe@example.com",
    phone: "+2349000000000",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 2,
    name: "Emily Johnson",
    role: "Registered Nurse",
    email: "emily.johnson@hospital.com",
    phone: "+2348123456789",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 3,
    name: "Michael Chen",
    role: "Radiologic Technologist",
    email: "michael.chen@medcenter.org",
    phone: "+2347987654321",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 4,
    name: "Sarah Williams",
    role: "Physical Therapist",
    email: "sarah.williams@rehab.net",
    phone: "+2346876543210",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 5,
    name: "David Rodriguez",
    role: "Medical Laboratory Technician",
    email: "david.rodriguez@labcare.com",
    phone: "+2345765432109",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 6,
    name: "Jessica Lee",
    role: "Occupational Therapist",
    email: "jessica.lee@wellness.org",
    phone: "+2344654321098",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 7,
    name: "Robert Taylor",
    role: "Emergency Medical Technician",
    email: "robert.taylor@ems.com",
    phone: "+2343543210987",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 8,
    name: "Amanda Martinez",
    role: "Surgical Technologist",
    email: "amanda.martinez@surgicenter.net",
    phone: "+2342432109876",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 9,
    name: "Christopher Kim",
    role: "Respiratory Therapist",
    email: "christopher.kim@lungs.org",
    phone: "+2341321098765",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 10,
    name: "Rachel Patel",
    role: "Diagnostic Medical Sonographer",
    email: "rachel.patel@imaging.com",
    phone: "+2340210987654",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 11,
    name: "Daniel Thompson",
    role: "Pharmacist",
    email: "daniel.thompson@pharmacy.net",
    phone: "+2349876543210",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 12,
    name: "Lauren Garcia",
    role: "Medical Assistant",
    email: "lauren.garcia@clinic.org",
    phone: "+2348765432109",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 13,
    name: "Kevin Wong",
    role: "Cardiovascular Technologist",
    email: "kevin.wong@heartcenter.com",
    phone: "+2347654321098",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 14,
    name: "Sophia Anderson",
    role: "Mental Health Counselor",
    email: "sophia.anderson@mentalhealth.org",
    phone: "+2346543210987",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 15,
    name: "Brian Miller",
    role: "Dental Hygienist",
    email: "brian.miller@dentalcare.com",
    phone: "+2345432109876",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 16,
    name: "Emma Rodriguez",
    role: "Nutritionist",
    email: "emma.rodriguez@wellness.com",
    phone: "+2344321098765",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 17,
    name: "Alexander Park",
    role: "Medical Technologist",
    email: "alexander.park@labmed.org",
    phone: "+2343210987654",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 18,
    name: "Olivia Chen",
    role: "Pediatric Nurse",
    email: "olivia.chen@childrensclinic.net",
    phone: "+2342109876543",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 19,
    name: "Nathan Kim",
    role: "Orthopedic Technician",
    email: "nathan.kim@bonecenter.com",
    phone: "+2341098765432",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 20,
    name: "Isabella Martinez",
    role: "Speech-Language Pathologist",
    email: "isabella.martinez@communication.org",
    phone: "+2340987654321",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 21,
    name: "Ethan Williams",
    role: "Dialysis Technician",
    email: "ethan.williams@kidneycare.net",
    phone: "+2349876543211",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 22,
    name: "Ava Thompson",
    role: "Radiology Nurse",
    email: "ava.thompson@imaging.com",
    phone: "+2348765432110",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 23,
    name: "Lucas Garcia",
    role: "Medical Records Technician",
    email: "lucas.garcia@healthrecords.org",
    phone: "+2347654321099",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 24,
    name: "Mia Johnson",
    role: "Clinical Laboratory Scientist",
    email: "mia.johnson@labscience.com",
    phone: "+2346543210988",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 25,
    name: "Noah Lee",
    role: "Pharmacy Technician",
    email: "noah.lee@drugstore.net",
    phone: "+2345432109877",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 26,
    name: "Sophia Patel",
    role: "Radiation Therapist",
    email: "sophia.patel@cancercenter.org",
    phone: "+2344321098766",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 27,
    name: "Jackson Wong",
    role: "Emergency Room Nurse",
    email: "jackson.wong@emergency.com",
    phone: "+2343210987655",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 28,
    name: "Aria Rodriguez",
    role: "Mental Health Nurse",
    email: "aria.rodriguez@psychiatry.net",
    phone: "+2342109876544",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 29,
    name: "Logan Chen",
    role: "Surgical Nurse",
    email: "logan.chen@surgicalunit.org",
    phone: "+2341098765433",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 30,
    name: "Harper Kim",
    role: "Rehabilitation Counselor",
    email: "harper.kim@rehab.com",
    phone: "+2340987654322",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 31,
    name: "Evelyn Martinez",
    role: "Cardiac Care Technician",
    email: "evelyn.martinez@heartcare.net",
    phone: "+2349876543212",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 32,
    name: "Mason Taylor",
    role: "Medical Social Worker",
    email: "mason.taylor@healthcare.org",
    phone: "+2348765432111",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 33,
    name: "Abigail Johnson",
    role: "Wound Care Specialist",
    email: "abigail.johnson@woundcare.com",
    phone: "+2347654321100",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 34,
    name: "Elijah Lee",
    role: "Anesthesia Technician",
    email: "elijah.lee@surgery.net",
    phone: "+2346543210989",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 35,
    name: "Emily Garcia",
    role: "Oncology Nurse",
    email: "emily.garcia@cancercare.org",
    phone: "+2345432109878",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 36,
    name: "Liam Rodriguez",
    role: "Ultrasound Technician",
    email: "liam.rodriguez@imaging.com",
    phone: "+2344321098767",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 37,
    name: "Charlotte Wong",
    role: "Neurological Nurse",
    email: "charlotte.wong@neurocare.net",
    phone: "+2343210987656",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 38,
    name: "Benjamin Patel",
    role: "Orthopedic Nurse",
    email: "benjamin.patel@boneclinic.org",
    phone: "+2342109876545",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 39,
    name: "Amelia Chen",
    role: "Cardiac Care Nurse",
    email: "amelia.chen@heartunit.com",
    phone: "+2341098765434",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 40,
    name: "Daniel Kim",
    role: "Respiratory Care Technician",
    email: "daniel.kim@breathewell.net",
    phone: "+2340987654323",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 41,
    name: "Emma Martinez",
    role: "Pediatric Medical Assistant",
    email: "emma.martinez@kidsclinic.org",
    phone: "+2349876543213",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 42,
    name: "Ryan Thompson",
    role: "Medical Imaging Technologist",
    email: "ryan.thompson@medimaging.com",
    phone: "+2348765432112",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 43,
    name: "Olivia Garcia",
    role: "Oncology Care Coordinator",
    email: "olivia.garcia@cancercenter.net",
    phone: "+2347654321101",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 44,
    name: "Jackson Lee",
    role: "Emergency Medical Technician",
    email: "jackson.lee@emservices.org",
    phone: "+2346543210990",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 45,
    name: "Sophia Wong",
    role: "Physical Therapy Assistant",
    email: "sophia.wong@rehabclinic.com",
    phone: "+2345432109879",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 46,
    name: "Ethan Rodriguez",
    role: "Medical Laboratory Technician",
    email: "ethan.rodriguez@labmed.net",
    phone: "+2344321098768",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 47,
    name: "Isabella Patel",
    role: "Dialysis Nurse",
    email: "isabella.patel@kidneycare.org",
    phone: "+2343210987657",
    status: OnboardingStatus.DEACTIVATED,
  },
  {
    id: 48,
    name: "Noah Chen",
    role: "Surgical Technologist",
    email: "noah.chen@surgicenter.com",
    phone: "+2342109876546",
    status: OnboardingStatus.ACTIVE,
  },
  {
    id: 49,
    name: "Ava Martinez",
    role: "Mental Health Counselor",
    email: "ava.martinez@mentalwellness.net",
    phone: "+2341098765435",
    status: OnboardingStatus.ON_LEAVE,
  },
  {
    id: 50,
    name: "Lucas Kim",
    role: "Radiology Nurse",
    email: "lucas.kim@radiologyunit.org",
    phone: "+2340987654324",
    status: OnboardingStatus.ACTIVE,
  }
];